# Disassembled from inst_la_mem.elf
# Generated by loongarch32r-linux-gnusf-objdump


inst_la_mem.elf:     file format elf32-loongarch


Disassembly of section .text:

1c000000 <_start>:
1c000000:	00101001 	add.w	$r1,$r0,$r4
1c000004:	001c0c41 	mul.w	$r1,$r2,$r3
1c000008:	001c0421 	mul.w	$r1,$r1,$r1
1c00000c:	29800001 	st.w	$r1,$r0,0
1c000010:	29801004 	st.w	$r4,$r0,4(0x4)
1c000014:	29802006 	st.w	$r6,$r0,8(0x8)
1c000018:	28800004 	ld.w	$r4,$r0,0
1c00001c:	29803004 	st.w	$r4,$r0,12(0xc)
1c000020:	28801004 	ld.w	$r4,$r0,4(0x4)
1c000024:	28803004 	ld.w	$r4,$r0,12(0xc)
1c000028:	29800006 	st.w	$r6,$r0,0
1c00002c:	28803006 	ld.w	$r6,$r0,12(0xc)
1c000030:	298000c6 	st.w	$r6,$r6,0
1c000034:	288000c4 	ld.w	$r4,$r6,0
1c000038:	29800005 	st.w	$r5,$r0,0
1c00003c:	28800005 	ld.w	$r5,$r0,0
1c000040:	28800006 	ld.w	$r6,$r0,0
1c000044:	28801004 	ld.w	$r4,$r0,4(0x4)
1c000048:	28802006 	ld.w	$r6,$r0,8(0x8)
1c00004c:	00101025 	add.w	$r5,$r1,$r4
1c000050:	00101847 	add.w	$r7,$r2,$r6
1c000054:	001c1842 	mul.w	$r2,$r2,$r6
1c000058:	00101066 	add.w	$r6,$r3,$r4
1c00005c:	001c18e7 	mul.w	$r7,$r7,$r6
1c000060:	00101ca5 	add.w	$r5,$r5,$r7
1c000064:	001c0ce3 	mul.w	$r3,$r7,$r3
1c000068:	00101801 	add.w	$r1,$r0,$r6
1c00006c:	00101003 	add.w	$r3,$r0,$r4
1c000070:	001c0c61 	mul.w	$r1,$r3,$r3
1c000074:	001c0421 	mul.w	$r1,$r1,$r1
1c000078:	00101025 	add.w	$r5,$r1,$r4
1c00007c:	00101847 	add.w	$r7,$r2,$r6
1c000080:	001c1842 	mul.w	$r2,$r2,$r6
1c000084:	00101066 	add.w	$r6,$r3,$r4
1c000088:	001c18e7 	mul.w	$r7,$r7,$r6
1c00008c:	00101ca5 	add.w	$r5,$r5,$r7
1c000090:	001c0ce3 	mul.w	$r3,$r7,$r3
1c000094:	00100000 	add.w	$r0,$r0,$r0
1c000098:	28800041 	ld.w	$r1,$r2,0
1c00009c:	29802001 	st.w	$r1,$r0,8(0x8)
1c0000a0:	29801002 	st.w	$r2,$r0,4(0x4)
1c0000a4:	28800042 	ld.w	$r2,$r2,0
1c0000a8:	28800043 	ld.w	$r3,$r2,0
1c0000ac:	28800044 	ld.w	$r4,$r2,0

# End of disassembly
