# Disassembled from inst_la_alu.elf
# Generated by loongarch32r-linux-gnusf-objdump


inst_la_alu.elf:     file format elf32-loongarch


Disassembly of section .text:

1c000000 <_start>:
1c000000:	00101001 	add.w	$r1,$r0,$r4
1c000004:	001c0c41 	mul.w	$r1,$r2,$r3
1c000008:	001c0421 	mul.w	$r1,$r1,$r1
1c00000c:	00101025 	add.w	$r5,$r1,$r4
1c000010:	00101847 	add.w	$r7,$r2,$r6
1c000014:	001c1842 	mul.w	$r2,$r2,$r6
1c000018:	00101066 	add.w	$r6,$r3,$r4
1c00001c:	001c18e7 	mul.w	$r7,$r7,$r6
1c000020:	00101ca5 	add.w	$r5,$r5,$r7
1c000024:	001c0ce3 	mul.w	$r3,$r7,$r3
1c000028:	00101801 	add.w	$r1,$r0,$r6
1c00002c:	00101003 	add.w	$r3,$r0,$r4
1c000030:	001c0c61 	mul.w	$r1,$r3,$r3
1c000034:	001c0421 	mul.w	$r1,$r1,$r1
1c000038:	00101025 	add.w	$r5,$r1,$r4
1c00003c:	00101847 	add.w	$r7,$r2,$r6
1c000040:	001c1842 	mul.w	$r2,$r2,$r6
1c000044:	00101066 	add.w	$r6,$r3,$r4
1c000048:	001c18e7 	mul.w	$r7,$r7,$r6
1c00004c:	00101ca5 	add.w	$r5,$r5,$r7
1c000050:	001c0ce3 	mul.w	$r3,$r7,$r3
1c000054:	00100000 	add.w	$r0,$r0,$r0
1c000058:	00100421 	add.w	$r1,$r1,$r1
1c00005c:	00100422 	add.w	$r2,$r1,$r1
1c000060:	00100423 	add.w	$r3,$r1,$r1
1c000064:	00100424 	add.w	$r4,$r1,$r1

# End of disassembly
