# Disassembled from inst_la_mem.elf
# Generated by loongarch32r-linux-gnusf-objdump


inst_la_mem.elf:     file format elf32-loongarch


Disassembly of section .text:

00010054 <_start>:
   10054:	00101001 	add.w	$r1,$r0,$r4
   10058:	001c0c41 	mul.w	$r1,$r2,$r3
   1005c:	001c0421 	mul.w	$r1,$r1,$r1
   10060:	29800001 	st.w	$r1,$r0,0
   10064:	29801004 	st.w	$r4,$r0,4(0x4)
   10068:	29802006 	st.w	$r6,$r0,8(0x8)
   1006c:	28800004 	ld.w	$r4,$r0,0
   10070:	29803004 	st.w	$r4,$r0,12(0xc)
   10074:	28801004 	ld.w	$r4,$r0,4(0x4)
   10078:	28803004 	ld.w	$r4,$r0,12(0xc)
   1007c:	29800006 	st.w	$r6,$r0,0
   10080:	28803006 	ld.w	$r6,$r0,12(0xc)
   10084:	298000c6 	st.w	$r6,$r6,0
   10088:	288000c4 	ld.w	$r4,$r6,0
   1008c:	29800005 	st.w	$r5,$r0,0
   10090:	28800005 	ld.w	$r5,$r0,0
   10094:	28800006 	ld.w	$r6,$r0,0
   10098:	28801004 	ld.w	$r4,$r0,4(0x4)
   1009c:	28802006 	ld.w	$r6,$r0,8(0x8)
   100a0:	00101025 	add.w	$r5,$r1,$r4
   100a4:	00101847 	add.w	$r7,$r2,$r6
   100a8:	001c1842 	mul.w	$r2,$r2,$r6
   100ac:	00101066 	add.w	$r6,$r3,$r4
   100b0:	001c18e7 	mul.w	$r7,$r7,$r6
   100b4:	00101ca5 	add.w	$r5,$r5,$r7
   100b8:	001c0ce3 	mul.w	$r3,$r7,$r3
   100bc:	00101801 	add.w	$r1,$r0,$r6
   100c0:	00101003 	add.w	$r3,$r0,$r4
   100c4:	001c0c61 	mul.w	$r1,$r3,$r3
   100c8:	001c0421 	mul.w	$r1,$r1,$r1
   100cc:	00101025 	add.w	$r5,$r1,$r4
   100d0:	00101847 	add.w	$r7,$r2,$r6
   100d4:	001c1842 	mul.w	$r2,$r2,$r6
   100d8:	00101066 	add.w	$r6,$r3,$r4
   100dc:	001c18e7 	mul.w	$r7,$r7,$r6
   100e0:	00101ca5 	add.w	$r5,$r5,$r7
   100e4:	001c0ce3 	mul.w	$r3,$r7,$r3
   100e8:	00100000 	add.w	$r0,$r0,$r0
   100ec:	28800041 	ld.w	$r1,$r2,0
   100f0:	29802001 	st.w	$r1,$r0,8(0x8)
   100f4:	29801002 	st.w	$r2,$r0,4(0x4)
   100f8:	28800042 	ld.w	$r2,$r2,0
   100fc:	28800043 	ld.w	$r3,$r2,0
   10100:	28800044 	ld.w	$r4,$r2,0

# End of disassembly
