# Disassembled from inst_la_alu.elf
# Generated by loongarch32r-linux-gnusf-objdump


inst_la_alu.elf:     file format elf32-loongarch


Disassembly of section .text:

00010054 <_start>:
   10054:	00101001 	add.w	$r1,$r0,$r4
   10058:	001c0c41 	mul.w	$r1,$r2,$r3
   1005c:	001c0421 	mul.w	$r1,$r1,$r1
   10060:	00101025 	add.w	$r5,$r1,$r4
   10064:	00101847 	add.w	$r7,$r2,$r6
   10068:	001c1842 	mul.w	$r2,$r2,$r6
   1006c:	00101066 	add.w	$r6,$r3,$r4
   10070:	001c18e7 	mul.w	$r7,$r7,$r6
   10074:	00101ca5 	add.w	$r5,$r5,$r7
   10078:	001c0ce3 	mul.w	$r3,$r7,$r3
   1007c:	00101801 	add.w	$r1,$r0,$r6
   10080:	00101003 	add.w	$r3,$r0,$r4
   10084:	001c0c61 	mul.w	$r1,$r3,$r3
   10088:	001c0421 	mul.w	$r1,$r1,$r1
   1008c:	00101025 	add.w	$r5,$r1,$r4
   10090:	00101847 	add.w	$r7,$r2,$r6
   10094:	001c1842 	mul.w	$r2,$r2,$r6
   10098:	00101066 	add.w	$r6,$r3,$r4
   1009c:	001c18e7 	mul.w	$r7,$r7,$r6
   100a0:	00101ca5 	add.w	$r5,$r5,$r7
   100a4:	001c0ce3 	mul.w	$r3,$r7,$r3
   100a8:	00100000 	add.w	$r0,$r0,$r0
   100ac:	00100421 	add.w	$r1,$r1,$r1
   100b0:	00100422 	add.w	$r2,$r1,$r1
   100b4:	00100423 	add.w	$r3,$r1,$r1
   100b8:	00100424 	add.w	$r4,$r1,$r1

# End of disassembly
